# Generated by Django 4.2.1 on 2023-05-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('usuario', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Textos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('texto', models.CharField(max_length=480)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=240)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.usuarios')),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.textos')),
            ],
        ),
    ]
